name: ktlint

on:
  pull_request:
    paths:
      - .github/workflows/ktlint.yml
      - '**/src/**/*.kt'
      - '**.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.41.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: run ktlint
        run: |
          ktlint "**/src/**/*.kt" --reporter=checkstyle,output=build/ktlint-report.xml
      - uses: yutailang0119/action-ktlint@v1.0.0
        with:
          xml_path: build/*.xml
