name: ktlint

on:
  pull_request:
    paths:
      - .github/workflows/ktlint.yml
      - '**/src/**/*.k'
      - '**.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Run ktlint
        uses: lucasnlm/ktlint-action@v1.0.1
